version: '3.3'

services:
  weight-tracker:
    image: magicadry/weight-tracker:latest
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - weight_data:/app/data
    environment:
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
      - RP_ID=weight-tracker.gosalvez.es
      - ORIGIN=https://weight-tracker.gosalvez.es
      - AEMET_API_KEY=${AEMET_API_KEY}
      - ALLOW_REGISTRATION=${ALLOW_REGISTRATION:-false}
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.weight-tracker-https.redirectscheme.scheme=https"
      - "traefik.http.routers.weight-tracker.entrypoints=web"
      - "traefik.http.routers.weight-tracker.middlewares=weight-tracker-https"
      - "traefik.http.routers.weight-tracker.rule=Host(`weight-tracker.gosalvez.es`)"
      - "traefik.http.routers.weight-tracker-secure.tls=true"
      - "traefik.http.routers.weight-tracker-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.weight-tracker-secure.entrypoints=websecure"
      - "traefik.http.routers.weight-tracker-secure.rule=Host(`weight-tracker.gosalvez.es`)"
      - "traefik.http.services.weight-tracker-secure.loadbalancer.server.port=3000"

networks:
  traefik:
    external: true

volumes:
  weight_data:
    driver: local
